# -*- coding: utf-8 -*-
"""program1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qCSzVIfsyoeFVc9eMYZAJn40Fg9laJyC
"""

n = int(input())
intervals = []

for _ in range(n):
    start, end = map(int, input().split())
    intervals.append((start, end))

intervals.sort(key=lambda x: x[0])

merged = []
for interval in intervals:
    if not merged or merged[-1][1] < interval[0]:
        merged.append(interval)
    else:
        merged[-1] = (merged[-1][0], max(merged[-1][1], interval[1]))

for start, end in merged:
    print(f"{start} {end}")