# -*- coding: utf-8 -*-
"""program3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qCSzVIfsyoeFVc9eMYZAJn40Fg9laJyC
"""

def solve():
    try:
        n = int(input().strip())
        l1 = list(map(int, input().split()))
        m = int(input().strip())
        l2 = list(map(int, input().split()))
    except EOFError:
        return

    result = []
    carry = 0
    i, j = 0, 0

    while i < n or j < m or carry:
        val1 = l1[i] if i < n else 0
        val2 = l2[j] if j < m else 0

        total = val1 + val2 + carry
        carry = total // 10
        result.append(str(total % 10))

        i += 1
        j += 1

    print(" ".join(result))

if __name__ == '__main__':
    solve()