# -*- coding: utf-8 -*-
"""program2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qCSzVIfsyoeFVc9eMYZAJn40Fg9laJyC
"""

from collections import deque

def solve():
    # Read inputs using standard input()
    try:
        n = int(input().strip())
        arr = list(map(int, input().split()))
        k = int(input().strip())
    except EOFError:
        return

    max_deque = deque()  # Stores indices of max values in decreasing order
    min_deque = deque()  # Stores indices of min values in increasing order

    left = 0
    max_len = 0
    best_start = 1  # 1-based index

    for right in range(n):
        # Maintain max deque
        while max_deque and arr[max_deque[-1]] <= arr[right]:
            max_deque.pop()
        max_deque.append(right)

        # Maintain min deque
        while min_deque and arr[min_deque[-1]] >= arr[right]:
            min_deque.pop()
        min_deque.append(right)

        # Shrink window if max - min > k
        while arr[max_deque[0]] - arr[min_deque[0]] > k:
            left += 1
            if max_deque[0] < left:
                max_deque.popleft()
            if min_deque[0] < left:
                min_deque.popleft()

        # Update maximum length and earliest starting position
        current_len = right - left + 1
        if current_len > max_len:
            max_len = current_len
            best_start = left + 1

    print(f"{max_len} {best_start}")

if __name__ == '__main__':
    solve()